name: lets_go_with_me
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1
  connectivity_plus: ^4.0.0
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.1.1

  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  logger: ^1.4.0
  flutter_otp_text_field: ^1.1.1
  dio: ^5.2.1+1
  image_picker: ^1.0.1
  image_cropper: ^5.0.0
  intl: ^0.17.0
  cached_network_image: ^3.3.1
  comment_tree: ^0.3.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Bold.ttf
          weight: 700


  uses-material-design: true
  assets:
    - assets/images/

